language: bash

sudo: false

branches:
  only:
    - master

before_script:
    - xmllint --version

# validate all *.xml files
script: find . -name "*.xml" -type f -print0 | xargs -0 xmllint --noout

# disable mail notifications
notifications:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
