name: lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - dev
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run basic linter on *.xml files

    steps:
      - uses: actions/checkout@v3

      - name: Install libxml2-utils package
        run: sudo apt install libxml2-utils

      - name: Check linter version
        run: xmllint --version

      - name: Validate *.xml files
        run: |
            find . -name "*.xml" -type f -print0 | xargs -0 xmllint --noout
